# Generated by Django 4.0.5 on 2026-02-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_room_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='profile_pic',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
