# Generated by Django 4.1.13 on 2026-02-12 22:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0007_message_room_user_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='direct_pair_key',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='room',
            name='kind',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('direct', 'Direct')], db_index=True, default='private', max_length=10),
        ),
        migrations.CreateModel(
            name='ChatRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member'), ('viewer', 'Viewer'), ('blocked', 'Blocked')], db_index=True, max_length=16)),
                ('username_snapshot', models.CharField(db_index=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_chat_roles', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='chat.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_roles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='chatrole',
            index=models.Index(fields=['room', 'role'], name='chat_role_room_role_idx'),
        ),
        migrations.AddConstraint(
            model_name='chatrole',
            constraint=models.UniqueConstraint(fields=('room', 'user'), name='chat_role_room_user_uniq'),
        ),
    ]
